// default package
// Generated Aug 4, 2016 3:39:00 PM by Hibernate Tools 4.3.1.Final
package com.mock.bookstore.model;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * BookDetail generated by hbm2java
 */
public class BookDetail implements java.io.Serializable {

	private int id;
	private Author author;
	private BookStore bookStore;
	private BookType bookType;
	private Producer producer;
	private String name;
	private String description;
	private Date publicedYear;
	private Set<OrderDetail> orderDetails = new HashSet<OrderDetail>(0);

	public BookDetail() {
	}

	public BookDetail(int id) {
		this.id = id;
	}

	public BookDetail(int id, Author author, BookStore bookStore, BookType bookType, Producer producer, String name,
			String description, Date publicedYear, Set<OrderDetail> orderDetails) {
		this.id = id;
		this.author = author;
		this.bookStore = bookStore;
		this.bookType = bookType;
		this.producer = producer;
		this.name = name;
		this.description = description;
		this.publicedYear = publicedYear;
		this.orderDetails = orderDetails;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public Author getAuthor() {
		return this.author;
	}

	public void setAuthor(Author author) {
		this.author = author;
	}

	public BookStore getBookStore() {
		return this.bookStore;
	}

	public void setBookStore(BookStore bookStore) {
		this.bookStore = bookStore;
	}

	public BookType getBookType() {
		return this.bookType;
	}

	public void setBookType(BookType bookType) {
		this.bookType = bookType;
	}

	public Producer getProducer() {
		return this.producer;
	}

	public void setProducer(Producer producer) {
		this.producer = producer;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public Date getPublicedYear() {
		return this.publicedYear;
	}

	public void setPublicedYear(Date publicedYear) {
		this.publicedYear = publicedYear;
	}

	public Set<OrderDetail> getOrderDetails() {
		return this.orderDetails;
	}

	public void setOrderDetails(Set<OrderDetail> orderDetails) {
		this.orderDetails = orderDetails;
	}

}
