// default package
// Generated Aug 4, 2016 3:39:00 PM by Hibernate Tools 4.3.1.Final
package com.mock.bookstore.model;

/**
 * OrderDetail generated by hbm2java
 */
public class OrderDetail implements java.io.Serializable {

	private int orderId;
	private BookDetail bookDetail;
	private Order order;
	private int qualtity;
	private Float unitPrice;
	private float totalPrice;

	public OrderDetail() {
	}

	public OrderDetail(BookDetail bookDetail, Order order, int qualtity, float totalPrice) {
		this.bookDetail = bookDetail;
		this.order = order;
		this.qualtity = qualtity;
		this.totalPrice = totalPrice;
	}

	public OrderDetail(BookDetail bookDetail, Order order, int qualtity, Float unitPrice, float totalPrice) {
		this.bookDetail = bookDetail;
		this.order = order;
		this.qualtity = qualtity;
		this.unitPrice = unitPrice;
		this.totalPrice = totalPrice;
	}

	public int getOrderId() {
		return this.orderId;
	}

	public void setOrderId(int orderId) {
		this.orderId = orderId;
	}

	public BookDetail getBookDetail() {
		return this.bookDetail;
	}

	public void setBookDetail(BookDetail bookDetail) {
		this.bookDetail = bookDetail;
	}

	public Order getOrder() {
		return this.order;
	}

	public void setOrder(Order order) {
		this.order = order;
	}

	public int getQualtity() {
		return this.qualtity;
	}

	public void setQualtity(int qualtity) {
		this.qualtity = qualtity;
	}

	public Float getUnitPrice() {
		return this.unitPrice;
	}

	public void setUnitPrice(Float unitPrice) {
		this.unitPrice = unitPrice;
	}

	public float getTotalPrice() {
		return this.totalPrice;
	}

	public void setTotalPrice(float totalPrice) {
		this.totalPrice = totalPrice;
	}

}
