// default package
// Generated Aug 4, 2016 3:39:00 PM by Hibernate Tools 4.3.1.Final
package com.mock.bookstore.model;

/**
 * Order generated by hbm2java
 */
public class Order implements java.io.Serializable {

	private int id;
	private UserDetail userDetailByUserEmail;
	private UserDetail userDetailByUserId;
	private OrderDetail orderDetail;

	public Order() {
	}

	public Order(int id, UserDetail userDetailByUserEmail, UserDetail userDetailByUserId) {
		this.id = id;
		this.userDetailByUserEmail = userDetailByUserEmail;
		this.userDetailByUserId = userDetailByUserId;
	}

	public Order(int id, UserDetail userDetailByUserEmail, UserDetail userDetailByUserId, OrderDetail orderDetail) {
		this.id = id;
		this.userDetailByUserEmail = userDetailByUserEmail;
		this.userDetailByUserId = userDetailByUserId;
		this.orderDetail = orderDetail;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public UserDetail getUserDetailByUserEmail() {
		return this.userDetailByUserEmail;
	}

	public void setUserDetailByUserEmail(UserDetail userDetailByUserEmail) {
		this.userDetailByUserEmail = userDetailByUserEmail;
	}

	public UserDetail getUserDetailByUserId() {
		return this.userDetailByUserId;
	}

	public void setUserDetailByUserId(UserDetail userDetailByUserId) {
		this.userDetailByUserId = userDetailByUserId;
	}

	public OrderDetail getOrderDetail() {
		return this.orderDetail;
	}

	public void setOrderDetail(OrderDetail orderDetail) {
		this.orderDetail = orderDetail;
	}

}
