// default package
// Generated Aug 4, 2016 3:39:00 PM by Hibernate Tools 4.3.1.Final
package com.mock.bookstore.model;

import java.util.HashSet;
import java.util.Set;

/**
 * UserType generated by hbm2java
 */
public class UserType implements java.io.Serializable {

	private Integer id;
	private String name;
	private String description;
	private Set<UserDetail> userDetails = new HashSet<UserDetail>(0);

	public UserType() {
	}

	public UserType(String name, String description, Set<UserDetail> userDetails) {
		this.name = name;
		this.description = description;
		this.userDetails = userDetails;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public Set<UserDetail> getUserDetails() {
		return this.userDetails;
	}

	public void setUserDetails(Set<UserDetail> userDetails) {
		this.userDetails = userDetails;
	}

}
