// default package
// Generated Aug 4, 2016 3:39:00 PM by Hibernate Tools 4.3.1.Final
package com.mock.bookstore.model;

import java.util.HashSet;
import java.util.Set;

/**
 * UserDetail generated by hbm2java
 */
public class UserDetail implements java.io.Serializable {

	private Integer id;
	private UserType userType;
	private String username;
	private String email;
	private String password;
	private Set<Order> ordersForUserEmail = new HashSet<Order>(0);
	private Set<Order> ordersForUserId = new HashSet<Order>(0);

	public UserDetail() {
	}

	public UserDetail(String username, String email) {
		this.username = username;
		this.email = email;
	}

	public UserDetail(UserType userType, String username, String email, String password, Set<Order> ordersForUserEmail,
			Set<Order> ordersForUserId) {
		this.userType = userType;
		this.username = username;
		this.email = email;
		this.password = password;
		this.ordersForUserEmail = ordersForUserEmail;
		this.ordersForUserId = ordersForUserId;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public UserType getUserType() {
		return this.userType;
	}

	public void setUserType(UserType userType) {
		this.userType = userType;
	}

	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public Set<Order> getOrdersForUserEmail() {
		return this.ordersForUserEmail;
	}

	public void setOrdersForUserEmail(Set<Order> ordersForUserEmail) {
		this.ordersForUserEmail = ordersForUserEmail;
	}

	public Set<Order> getOrdersForUserId() {
		return this.ordersForUserId;
	}

	public void setOrdersForUserId(Set<Order> ordersForUserId) {
		this.ordersForUserId = ordersForUserId;
	}

}
